//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8zip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_8zip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data.
        /// </summary>
        internal static string BuildForm_OkButton_Click_Input_data {
            get {
                return ResourceManager.GetString("BuildForm_OkButton_Click_Input_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Program_Main_Done_ {
            get {
                return ResourceManager.GetString("Program_Main_Done_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to extract.
        /// </summary>
        internal static string Program_Main_Fail_to_extract {
            get {
                return ResourceManager.GetString("Program_Main_Fail_to_extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.zip was not found.
        /// </summary>
        internal static string ProgressBar_ExtractButton_Click___zip_was_not_found {
            get {
                return ResourceManager.GetString("ProgressBar_ExtractButton_Click___zip_was_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ProgressBar_GetRecPackButton_Click_Done {
            get {
                return ResourceManager.GetString("ProgressBar_GetRecPackButton_Click_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string ProgressBar_GetRecPackButton_Click_Done_ {
            get {
                return ResourceManager.GetString("ProgressBar_GetRecPackButton_Click_Done_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServicePack downloaded successfully.
        /// </summary>
        internal static string ProgressBar_GetRecPackButton_Click_ServicePack_downloaded_successfully {
            get {
                return ResourceManager.GetString("ProgressBar_GetRecPackButton_Click_ServicePack_downloaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove zip packages?.
        /// </summary>
        internal static string ProgressBar_progressBar2_Click_Do_you_want_to_remove_zip_packages_ {
            get {
                return ResourceManager.GetString("ProgressBar_progressBar2_Click_Do_you_want_to_remove_zip_packages_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string ProgressBar_progressBar2_Click_Done_ {
            get {
                return ResourceManager.GetString("ProgressBar_progressBar2_Click_Done_", resourceCulture);
            }
        }
    }
}
